import { Injectable } from '@angular/core';
import { Dish } from '../../restaurant/restaurant.model';
import { BehaviorSubject, map, Observable } from 'rxjs';
import { CartDto, CartItemDto } from '../cartDTO';
import { OrderDto, OrderItemDto, OrderStatus } from '../../order/orderDTO';

@Injectable({
  providedIn: 'root',
})
export class CartService {

  private cart :  CartDto = {} as CartDto;
  private cartItemsSubject = new BehaviorSubject<CartItemDto[]>([]);
  cartItems$ = this.cartItemsSubject.asObservable();
  serviceFee = 0.1; //replace with database call

  constructor() {
    const saved = localStorage.getItem('cart');
    if (saved) {
      this.cartItemsSubject.next(JSON.parse(saved));
    }

    // automatisch speichern bei jeder Änderung
    this.cartItems$.subscribe(items => localStorage.setItem('cart', JSON.stringify(items)));
  }

  addDish(dish: Dish, restaurantId: string | undefined) {
    const item: CartItemDto = {
      dishId: dish.id,
      name: dish.name,
      price: dish.price,
      quantity: 1,
      pictureUrl: dish.pictureUrl
    };

    if(this.cart.restaurantId === undefined){
      this.cart.restaurantId = restaurantId!;
    }

    this.addItem(item);
  }

  addItem(item: CartItemDto) {
    const items = this.cartItemsSubject.value;
    const existing = items.find(i => i.dishId === item.dishId);

    if (existing) {
      existing.quantity++;
    } else {
      items.push(item);
    }

    // Subject push → UI updated automatisch
    this.updateCart(items);
  }

  removeItem(dishId: number) {
    const items = this.cartItemsSubject.value.filter(i => i.dishId !== dishId);
    this.updateCart(items);
  }

  removeOneItem(dishId: number){
    const items = this.cartItemsSubject.value;
    const item = this.getItemById(dishId);
    if(item === undefined) return;
    if(item.quantity > 1) {
      item.quantity--;
      this.updateCart(items);
    } else if(item.quantity === 1) {
      this.removeItem(dishId);
    }
  }
  
  placeOrder() {
    const items = this.getOrderItems();
    const order : OrderDto = {
      id: '', // to be generated by backend
      restaurantId: this.cart.restaurantId,
      customerId: 0, // to be set based on logged in user 
      status: OrderStatus.PENDING,
      subtotalAmount: this.cartItemsSubject.value.reduce((sum, i) => sum + i.price * i.quantity, 0),
      discountAmount: 0,
      totalAmount: this.cart.totalPrice,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      items: items,
    };

    

  }

  

  clearCart() {
    this.cartItemsSubject.next([]);
  }

  get totalPrice$(): Observable<number> {
    return this.cartItems$.pipe(
      map(items => {
        const sum = items.reduce((acc, i) => acc + i.price * i.quantity, 0);
        const total = sum + sum * this.serviceFee;
        this.cart.totalPrice = total;
        return total;
      })
    );
  }

  getItemById(dishId: number) : CartItemDto | undefined{
    return this.cartItemsSubject.value.find(item => item.dishId === dishId);
  }

  private updateCart(items: CartItemDto[]) {
    this.cart.items = items;
    this.cartItemsSubject.next(items);
    this.totalPrice$;
  }

  private getOrderItems(): OrderItemDto[] {
    const orderItems: OrderItemDto[] = [];
    for(const item of this.cart.items){
      orderItems.push({
        id: 0, // to be generated by backend
        orderId: '', // to be set by backend
        dishId: item.dishId,
        name: item.name,
        unitPrice: item.price,
        quantity: item.quantity,
        totalPrice: item.price * item.quantity,
        createdAt: new Date().toISOString(),
      });
    }
    return orderItems;
  }
}
